[package]
name = "flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
flow-derive = { path = "flow-derive" }
serde = { version = "1.0.166", features = ["derive", "rc"] }
serde_json = "1.0.100"
wasm-bindgen = "0.2.87"
boa_engine = "0.17.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.37"
